# encoding: utf-8
"""
    Define path locations and helpful functions
"""

import os

# where to locate mp3s and m4as
audio_path = '../Audio'

# where to find .beats.txt files generated by DBNBeatTracker
beats_path = '../Audio/beats'

# where we can cache generated features
mls_path = '../Audio/features'

# where to find SALAMI annotations
annotations_path =  '../Data/salami-data-public/annotations/'

viz_path = '../Audio/viz'

def remove_suffix(filename):
     return os.path.splitext(os.path.basename(filename))[0]

def with_suffix(path, ext):
     return remove_suffix(path) + '.' + ext

def get_audio_cache_path(audio_filename, ext):
     return os.path.join(mls_path, remove_suffix(audio_filename) + ext)

